// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv_rNptX-gq_kWHz9Gvm5Zlh6wxJQvB5M',
    appId: '1:864730614736:web:a341d9d2e07aca6c8b47d5',
    messagingSenderId: '864730614736',
    projectId: 'ankh-project',
    authDomain: 'ankh-project.firebaseapp.com',
    storageBucket: 'ankh-project.firebasestorage.app',
    measurementId: 'G-P3N0S3YNEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfWRuc3Jjamw90iWvRZrLBx1Fcpa8Mqs0',
    appId: '1:864730614736:android:a9dd2fb56e6ff8908b47d5',
    messagingSenderId: '864730614736',
    projectId: 'ankh-project',
    storageBucket: 'ankh-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKEpXZ5lSAh1JRPPX8MCz9h_3Ehe5xUUU',
    appId: '1:864730614736:ios:e9158de31406f3798b47d5',
    messagingSenderId: '864730614736',
    projectId: 'ankh-project',
    storageBucket: 'ankh-project.firebasestorage.app',
    iosBundleId: 'com.example.ankhProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKEpXZ5lSAh1JRPPX8MCz9h_3Ehe5xUUU',
    appId: '1:864730614736:ios:e9158de31406f3798b47d5',
    messagingSenderId: '864730614736',
    projectId: 'ankh-project',
    storageBucket: 'ankh-project.firebasestorage.app',
    iosBundleId: 'com.example.ankhProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv_rNptX-gq_kWHz9Gvm5Zlh6wxJQvB5M',
    appId: '1:864730614736:web:3276982777fae1fc8b47d5',
    messagingSenderId: '864730614736',
    projectId: 'ankh-project',
    authDomain: 'ankh-project.firebaseapp.com',
    storageBucket: 'ankh-project.firebasestorage.app',
    measurementId: 'G-TGQ85M15G1',
  );
}
